name: "Kubernetes Auth"
listen: "0.0.0.0:5555"
oidc:
  client:
    id: "example-app"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    redirect_url: "https://loginapp.192.168.1.110.xip.io:5555/callback"
  issuer:
    root_ca: "/ssl/ca.pem"
    url: "https://dex.192.168.1.110.xip.io:32000"
  extra_scopes:
    - groups
  offline_as_scope: true
  cross_clients:
  - web
tls:
  enabled: true
  cert: /ssl/cert.pem
  key: /ssl/key.pem
log:
  level: Debug
  format: json
web_output:
  main_client_id: "example-app"
  main_username_claim: "email"
  assets_dir: "./assets/"
  skip_main_page: false
